version: '3.2'
services:
  service:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        ENTRY: 'service'
        ENVIRONMENT: '${ENVIRONMENT}'
    ports:
      - '10001:10001'
    restart: 'no'
